'use client';
import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
type Photo={id:string,title:string,priceCents:number};
export default function Checkout(){const [ids,setIds]=useState<string[]>([]);const [photos,setPhotos]=useState<Photo[]>([]);const [email,setEmail]=useState("");const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{setIds(JSON.parse(localStorage.getItem('tong_an_cart')||'[]'));fetch('/api/photos').then(r=>r.json()).then(setPhotos)},[]);
 const items=useMemo(()=>ids.map(id=>photos.find(p=>p.id===id)).filter(Boolean) as Photo[],[ids,photos]);const total=items.reduce((s,p)=>s+p.priceCents,0);
 async function create(){setError("");if(!email||items.length===0){setError("Please add a photo and enter your email.");return}setBusy(true);const r=await fetch('/api/orders',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({email,items:ids.map(photoId=>({photoId,quantity:1}))})});const d=await r.json();if(!r.ok){setError(d.error||'Could not create order');setBusy(false);return}localStorage.removeItem('tong_an_cart');location.href=`/order/${d.accessToken}`}
 return <main className="container section checkout-grid"><div><p className="eyebrow">CHECKOUT</p><h1>Complete Your Order</h1><p className="lead">Enter your email. You will receive a secure order page for QR payment and download access after verification.</p><div className="card form-card"><label className="label">Email address</label><input className="input" type="email" placeholder="you@example.com" value={email} onChange={e=>setEmail(e.target.value)}/>{error&&<p className="error">{error}</p>}<button className="btn btn-gold" onClick={create} disabled={busy}>{busy?'Creating order…':'Create Order & Show QR'}</button></div></div><aside className="card summary"><h2>Order Summary</h2>{items.map(p=><div className="summary-row" key={p.id}><span>{p.title}</span><strong>${(p.priceCents/100).toFixed(2)}</strong></div>)}<div className="summary-total"><span>Total</span><strong>${(total/100).toFixed(2)}</strong></div><Link href="/cart" className="muted">← Back to cart</Link></aside></main>}
